import { RegulationTopic, SemanticTable, ToolCatalogItem } from './chatbot.types';

export const TOOL_CATALOG: ToolCatalogItem[] = [
  {
    name: 'student.profile',
    description: 'Datos academicos principales del alumno autenticado.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Perfil del alumno, carrera, plan, semestre y estatus.',
    tags: ['perfil', 'alumno', 'datos_personales'],
  },
  {
    name: 'student.schedule',
    description: 'Horario inscrito del alumno autenticado en el periodo activo.',
    roles: ['alumno'],
    parameters: {
      day: 'Dia de la semana opcional para filtrar, por ejemplo lunes.',
    },
    returns: 'Lista de materias, grupos, profesor, dia, hora y aula.',
    tags: ['horario', 'clases', 'inscripcion'],
  },
  {
    name: 'student.kardex',
    description: 'Historial academico y avance del alumno autenticado.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Materias cursadas, calificaciones, resultado, promedio y avance.',
    tags: ['kardex', 'historial', 'promedio', 'avance'],
  },
  {
    name: 'student.grades',
    description: 'Calificaciones del alumno autenticado en el periodo activo.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Evaluaciones, calificacion, profesor, materia y grupo.',
    tags: ['calificaciones', 'parcial', 'evaluacion'],
  },
  {
    name: 'student.reenrollment_status',
    description: 'Estado de cita y ventana de reinscripcion del alumno autenticado.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Estado, mensaje, cita y periodo cuando existan.',
    tags: ['reinscripcion', 'cita', 'periodo'],
  },
  {
    name: 'student.reenrollment_eligibility',
    description: 'Grupos elegibles para reinscripcion del alumno autenticado.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Grupos disponibles filtrados por prerrequisitos, cupo y choques.',
    tags: ['reinscripcion', 'materias', 'grupos', 'prerrequisitos'],
  },
  {
    name: 'student.withdrawals_status',
    description: 'Estado de bajas y materias inscritas que puede evaluar el alumno autenticado.',
    roles: ['alumno'],
    parameters: {},
    returns: 'Ventana de baja, creditos minimos, creditos inscritos y materias activas.',
    tags: ['bajas', 'materias', 'creditos'],
  },
  {
    name: 'teacher.profile',
    description: 'Datos principales del profesor autenticado.',
    roles: ['profesor'],
    parameters: {},
    returns: 'Numero de empleado, departamento, correo y estatus.',
    tags: ['perfil', 'profesor'],
  },
  {
    name: 'teacher.schedule',
    description: 'Horario y sesiones asignadas al profesor autenticado.',
    roles: ['profesor'],
    parameters: {
      day: 'Dia de la semana opcional para filtrar, por ejemplo lunes.',
    },
    returns: 'Grupos, materias, horarios y aulas del profesor.',
    tags: ['horario', 'profesor', 'grupos'],
  },
  {
    name: 'teacher.groups',
    description: 'Grupos asignados al profesor autenticado.',
    roles: ['profesor'],
    parameters: {},
    returns: 'Materia, clave de grupo, cupo, creditos y horario resumido.',
    tags: ['grupos', 'cupo', 'profesor'],
  },
  {
    name: 'teacher.group_students',
    description: 'Alumnos inscritos en un grupo asignado al profesor autenticado.',
    roles: ['profesor'],
    parameters: {
      group_key: 'Clave visible del grupo, por ejemplo 4CM2. Opcional si solo tiene un grupo.',
    },
    returns: 'Boleta, nombre y correo de alumnos del grupo autorizado.',
    tags: ['alumnos', 'lista', 'grupo'],
  },
];

export const REGULATION_TOPICS: RegulationTopic[] = [
  {
    id: 'reinscripcion',
    title: 'Reinscripcion',
    description: 'Reglas de cargas, creditos, adeudos, cita y continuidad academica.',
    keywords: ['reinscripcion', 'creditos', 'carga', 'adeudos', 'cita'],
  },
  {
    id: 'baja_materias',
    title: 'Baja de materias',
    description: 'Ventana, restricciones, carga minima y casos en los que procede una baja.',
    keywords: ['baja', 'materia', 'carga minima', 'recursando'],
  },
  {
    id: 'ets',
    title: 'ETS',
    description: 'Evaluacion a titulo de suficiencia y condiciones generales.',
    keywords: ['ets', 'titulo de suficiencia', 'evaluacion'],
  },
  {
    id: 'calificaciones',
    title: 'Calificaciones y revisiones',
    description: 'Escala, revision, responsabilidades docentes y plazos.',
    keywords: ['calificaciones', 'revision', 'profesor', 'docente'],
  },
  {
    id: 'gestion_escolar',
    title: 'Gestion escolar',
    description: 'Tramites, documentos, dictamen, justificantes y solicitudes academicas.',
    keywords: ['gestion', 'documentos', 'dictamen', 'justificantes'],
  },
  {
    id: 'portal_saes',
    title: 'Uso del portal SAES 2.0',
    description: 'Navegacion y acciones disponibles para alumnos y profesores.',
    keywords: ['portal', 'saes', 'horario', 'asistencia', 'anuncios'],
  },
];

export const SEMANTIC_DB_CATALOG: SemanticTable[] = [
  {
    table: 'alumno',
    description: 'Identidad escolar y plan del alumno.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_alumno: 'Identificador interno del alumno.',
      id_usuario: 'Usuario autenticado asociado.',
      boleta: 'Identificador escolar. Debe salir del contexto autenticado.',
      id_plan: 'Plan de estudios del alumno.',
      semestre_actual: 'Semestre actual registrado.',
      estatus: 'Estado academico.',
    },
    relations: ['alumno.id_usuario -> usuario.id_usuario', 'alumno.id_plan -> plan_estudios.id_plan'],
    rules: [
      'Nunca filtrar por boleta escrita por el usuario.',
      'Alumnos: datos personales requieren alumno.id_usuario = :authUserId.',
      'Profesores: pueden leer datos de alumnos inscritos en sus grupos via JOIN inscripcion i ON a.id_alumno = i.id_alumno JOIN grupo g ON i.id_grupo = g.id_grupo WHERE g.id_profesor = (SELECT id_profesor FROM profesor WHERE id_usuario = :authUserId).',
    ],
  },
  {
    table: 'usuario',
    description: 'Nombre y datos de contacto del usuario. Solo columnas de identidad publica.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_usuario: 'Identificador del usuario.',
      nombre: 'Nombre del usuario.',
      apellido_paterno: 'Apellido paterno.',
      apellido_materno: 'Apellido materno.',
      correo_contacto: 'Correo de contacto.',
    },
    relations: ['usuario.id_usuario -> alumno.id_usuario', 'usuario.id_usuario -> profesor.id_usuario'],
    rules: [
      'Alumnos: solo su propio registro (WHERE id_usuario = :authUserId).',
      'Profesores: pueden leer nombre y correo de alumnos de sus grupos via JOIN alumno + inscripcion + grupo WHERE g.id_profesor = (SELECT id_profesor FROM profesor WHERE id_usuario = :authUserId).',
      'Nunca exponer hash_contrasena, salt ni campos de autenticacion.',
    ],
  },
  {
    table: 'inscripcion',
    description: 'Materias inscritas por alumnos.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_inscripcion: 'Identificador de inscripcion.',
      id_alumno: 'Alumno inscrito.',
      id_grupo: 'Grupo inscrito.',
      estatus: 'Estado de la inscripcion.',
    },
    relations: ['inscripcion.id_alumno -> alumno.id_alumno', 'inscripcion.id_grupo -> grupo.id_grupo'],
    rules: ['Alumnos solo pueden ver sus propias inscripciones.', 'Profesores solo grupos asignados.'],
  },
  {
    table: 'grupo',
    description: 'Oferta de grupos por periodo, materia y profesor.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_grupo: 'Identificador interno del grupo.',
      id_periodo: 'Periodo academico.',
      id_materia: 'Materia impartida.',
      id_profesor: 'Profesor asignado.',
      clave_grupo: 'Clave visible del grupo.',
      cupo_max: 'Cupo maximo.',
      cupo_actual: 'Cupo actual.',
      estatus: 'Estado del grupo.',
    },
    relations: ['grupo.id_materia -> materia.id_materia', 'grupo.id_profesor -> profesor.id_profesor'],
    rules: ['No mostrar grupos cancelados salvo que se solicite administrativamente.'],
  },
  {
    table: 'materia',
    description: 'Unidades de aprendizaje.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_materia: 'Identificador de materia.',
      clave: 'Clave oficial.',
      nombre: 'Nombre de la materia.',
      creditos: 'Creditos de la materia.',
    },
    relations: ['materia.id_materia -> plan_materia.id_materia'],
    rules: ['Puede consultarse como catalogo academico.'],
  },
  {
    table: 'historial_academico',
    description: 'Kardex y resultados historicos del alumno por periodo.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_alumno: 'Alumno propietario del registro.',
      id_materia: 'Materia cursada.',
      id_periodo: 'Periodo cursado.',
      calificacion_final: 'Calificacion final.',
      tipo_acreditacion: 'Forma de acreditacion.',
      resultado: 'Aprobado o reprobado.',
    },
    relations: ['historial_academico.id_alumno -> alumno.id_alumno', 'historial_academico.id_materia -> materia.id_materia'],
    rules: [
      'Alumnos: filtrar siempre por alumno autenticado (alumno.id_usuario = :authUserId).',
      'Profesores: pueden consultar historial de alumnos inscritos en sus grupos, filtrando via JOIN inscripcion i ON i.id_alumno = ha.id_alumno JOIN grupo g ON i.id_grupo = g.id_grupo WHERE g.id_profesor = (SELECT id_profesor FROM profesor WHERE id_usuario = :authUserId).',
    ],
  },
  {
    table: 'calificacion',
    description: 'Calificaciones capturadas por evaluacion parcial o final para cada alumno inscrito en el periodo activo.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_calificacion: 'Identificador de la calificacion.',
      id_inscripcion: 'Inscripcion del alumno en el grupo.',
      id_grupo_evaluacion: 'Ventana de evaluacion (parcial 1, parcial 2, final).',
      calificacion: 'Calificacion numerica de 0 a 10.',
      fecha_captura: 'Cuando fue capturada la calificacion.',
    },
    relations: [
      'calificacion.id_inscripcion -> inscripcion.id_inscripcion',
      'calificacion.id_grupo_evaluacion -> grupo_evaluacion.id_grupo_evaluacion',
    ],
    rules: [
      'Alumnos: filtrar siempre via inscripcion.id_alumno = (SELECT id_alumno FROM alumno WHERE id_usuario = :authUserId).',
      'Profesores: filtrar via JOIN grupo g ON i.id_grupo = g.id_grupo WHERE g.id_profesor = (SELECT id_profesor FROM profesor WHERE id_usuario = :authUserId). Solo grupos asignados al profesor autenticado.',
    ],
  },
  {
    table: 'grupo_evaluacion',
    description: 'Ventanas de evaluacion por grupo: Parcial 1, Parcial 2, Final, Extraordinario.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_grupo_evaluacion: 'Identificador de la ventana de evaluacion.',
      id_grupo: 'Grupo al que pertenece la evaluacion.',
      id_tipo_evaluacion: 'Tipo de evaluacion (parcial, final, etc.).',
      fecha_apertura: 'Cuando abre la ventana de captura.',
      fecha_cierre: 'Cuando cierra la ventana.',
      cerrada: 'Si la evaluacion ya fue cerrada (1) o sigue abierta (0).',
    },
    relations: ['grupo_evaluacion.id_grupo -> grupo.id_grupo', 'grupo_evaluacion.id_tipo_evaluacion -> tipo_evaluacion.id_tipo_evaluacion'],
    rules: ['Mismos permisos de acceso que el grupo al que pertenece.'],
  },
  {
    table: 'tipo_evaluacion',
    description: 'Catalogo de tipos de evaluacion con su ponderacion. Parcial 1=30%, Parcial 2=30%, Final=40%, Extraordinario=100%.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_tipo_evaluacion: 'Identificador del tipo.',
      nombre: 'Nombre descriptivo (Parcial 1, Parcial 2, Final, Extraordinario).',
      ponderacion: 'Peso porcentual en la calificacion final (30, 30, 40, 100).',
    },
    relations: [],
    rules: ['Catalogo de solo lectura. No contiene datos personales de alumnos.'],
  },
  {
    table: 'horario_grupo',
    description: 'Sesiones semanales de cada grupo.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_grupo: 'Grupo al que pertenece la sesion.',
      dia_semana: 'Dia de clase.',
      hora_inicio: 'Hora inicial.',
      hora_fin: 'Hora final.',
      id_aula: 'Aula asignada.',
    },
    relations: ['horario_grupo.id_grupo -> grupo.id_grupo', 'horario_grupo.id_aula -> aula.id_aula'],
    rules: ['Debe respetar permisos del grupo consultado.'],
  },
  {
    table: 'periodo_academico',
    description: 'Periodos academicos y periodo activo.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_periodo: 'Identificador del periodo.',
      nombre: 'Nombre del periodo.',
      fecha_inicio: 'Inicio.',
      fecha_fin: 'Fin.',
      activo: 'Indica periodo activo.',
    },
    relations: ['periodo_academico.id_periodo -> grupo.id_periodo'],
    rules: ['Puede consultarse para ubicar el periodo activo.'],
  },
  {
    table: 'aula',
    description: 'Catálogo de aulas disponibles en ESCOM con edificio y capacidad.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_aula: 'Identificador del aula.',
      nombre: 'Nombre del aula (ej: A-101).',
      edificio: 'Edificio donde se ubica.',
      capacidad: 'Capacidad máxima de personas.',
    },
    relations: ['aula.id_aula -> horario_grupo.id_aula'],
    rules: ['Catálogo de solo lectura. No contiene datos personales.'],
  },
  {
    table: 'carrera',
    description: 'Carreras académicas disponibles en ESCOM (ISC, IIA, LCD).',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_carrera: 'Identificador de la carrera.',
      nombre: 'Nombre completo de la carrera.',
      clave: 'Clave de la carrera (ej: ISC).',
    },
    relations: ['carrera.id_carrera -> plan_estudios.id_carrera'],
    rules: ['Catálogo de solo lectura.'],
  },
  {
    table: 'plan_estudios',
    description: 'Plan de estudios de cada carrera. Los alumnos están asociados a un plan con total_creditos y total_materias.',
    roles: ['alumno', 'admin'],
    columns: {
      id_plan: 'Identificador del plan.',
      id_carrera: 'Carrera a la que pertenece.',
      nombre: 'Nombre del plan de estudios (ej: Plan 2020).',
      anio_inicio: 'Año de inicio del plan.',
      total_creditos: 'Total de créditos del plan.',
      total_materias: 'Total de materias del plan.',
    },
    relations: ['plan_estudios.id_plan -> alumno.id_plan', 'plan_estudios.id_carrera -> carrera.id_carrera'],
    rules: ['Alumnos: su plan está en alumno.id_plan. Consultar para información sobre su programa académico.'],
  },
  {
    table: 'cita_reinscripcion',
    description: 'Citas asignadas a alumnos para el proceso de reinscripción — fecha y horario de la ventana de cada alumno.',
    roles: ['alumno', 'admin'],
    columns: {
      id_cita: 'Identificador de la cita.',
      id_alumno: 'Alumno al que pertenece la cita.',
      id_periodo: 'Periodo para el que aplica.',
      fecha_cita: 'Fecha de la cita de reinscripción.',
      hora_inicio: 'Hora de inicio de la ventana.',
      hora_fin: 'Hora de fin de la ventana.',
      estatus: 'Estado: pendiente, usada, cancelada.',
    },
    relations: ['cita_reinscripcion.id_alumno -> alumno.id_alumno', 'cita_reinscripcion.id_periodo -> periodo_academico.id_periodo'],
    rules: ['Alumnos: solo su propia cita (WHERE id_alumno = (SELECT id_alumno FROM alumno WHERE id_usuario = :authUserId)).'],
  },
  {
    table: 'proceso_academico',
    description: 'Catálogo de procesos académicos: Inscripcion inicial, Reinscripcion, Registro de calificaciones, Baja de materias, ETS, Revision de calificaciones.',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_proceso: 'Identificador del proceso.',
      nombre: 'Nombre del proceso académico.',
      descripcion: 'Descripción del proceso.',
    },
    relations: ['proceso_academico.id_proceso -> periodo_proceso.id_proceso'],
    rules: ['Catálogo de solo lectura. Usar junto con periodo_proceso para encontrar fechas de ventanas activas.'],
  },
  {
    table: 'periodo_proceso',
    description: 'Ventanas de fechas para cada proceso académico por periodo. Indica cuándo abre/cierra cada proceso (inscripcion, registro de calificaciones, bajas, ETS, etc.).',
    roles: ['alumno', 'profesor', 'admin'],
    columns: {
      id_periodo_proceso: 'Identificador de la ventana.',
      id_periodo: 'Periodo académico al que pertenece.',
      id_proceso: 'Proceso académico (JOIN proceso_academico para el nombre).',
      fecha_inicio: 'Fecha en que abre el proceso.',
      fecha_fin: 'Fecha en que cierra el proceso.',
      activo: 'Si el proceso está actualmente activo (1=activo, 0=cerrado).',
    },
    relations: [
      'periodo_proceso.id_periodo -> periodo_academico.id_periodo',
      'periodo_proceso.id_proceso -> proceso_academico.id_proceso',
    ],
    rules: [
      'Catálogo de solo lectura. No contiene datos personales.',
      "Para buscar la fecha límite de un proceso: SELECT pp.fecha_inicio, pp.fecha_fin FROM periodo_proceso pp JOIN proceso_academico pa ON pp.id_proceso = pa.id_proceso JOIN periodo_academico per ON pp.id_periodo = per.id_periodo WHERE per.activo = 1 AND pa.nombre LIKE '%calificaciones%'.",
    ],
  },
  {
    table: 'profesor',
    description: 'Identidad docente y departamento.',
    roles: ['profesor', 'admin'],
    columns: {
      id_profesor: 'Identificador interno del profesor.',
      id_usuario: 'Usuario autenticado asociado.',
      numero_empleado: 'Numero de empleado.',
      id_departamento: 'Departamento.',
      estatus: 'Estado docente.',
    },
    relations: ['profesor.id_usuario -> usuario.id_usuario', 'profesor.id_profesor -> grupo.id_profesor'],
    rules: ['Profesores solo pueden consultar datos propios o grupos asignados.'],
  },
];

export function getToolsForRoles(roles: string[]): ToolCatalogItem[] {
  return TOOL_CATALOG.filter((tool) => tool.roles.some((role) => roles.includes(role)));
}

export function getSemanticTablesForRoles(roles: string[]): SemanticTable[] {
  return SEMANTIC_DB_CATALOG.filter((table) => table.roles.some((role) => roles.includes(role)));
}
